In [2]:
#пример 1.2.1
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


In [4]:
#пример 1.2.2
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


In [5]:
#пример 1.2.3
Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.019182528353261286 0.9993536485907808 0.49962482238298833


In [6]:
#пример 1.2.4
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [7]:
#пример 1.2.5
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [8]:
#пример 1.2.6
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [12]:
#задание 1.3.1
A = np.zeros((4,4))
A[1::2,::2] = 1 #выбираем строки с нечетными индексами и каждый второй столбец.
A[0::2,1::2] = 1 #выбираем строки с четными индексами и каждый второй столбец
print(A)


[[0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 1. 0.]]


In [17]:
#задание 1.3.2
A = np.zeros((5,5))
A += np.arange(5)
print(A)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [21]:
#задание 1.3.3
A = np.random.random((3,3,3))
print(A)

[[[0.61601796 0.63642509 0.07204974]
  [0.88440998 0.30404858 0.84136738]
  [0.01838339 0.8587916  0.8420926 ]]

 [[0.25582609 0.46555227 0.07428738]
  [0.64256406 0.54333963 0.23339014]
  [0.64960066 0.40040752 0.5894083 ]]

 [[0.75494382 0.56252717 0.64329275]
  [0.44789444 0.52574391 0.71541319]
  [0.72967687 0.42977171 0.53356579]]]


In [28]:
#задание 1.3.4
A = np.zeros((5,5))
A[0::1,::4] = 1
A[0::4,1::1] = 1
print(A)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
#задание 1.3.5
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr)[::-1])

[8 7 6 5 4 3 2 1]


In [32]:
#задание 1.3.6
a = int(input('Введите кол-во строк:'))
b = int(input('Введите кол-во столбцов:'))
A = np.zeros((a, b), int)

print(A)
print(np.shape(A)) # форма
print(np.size(A)) # размер
print(np.ndim(A)) # размерность


Введите кол-во строк: 3
Введите кол-во столбцов: 3


[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)
9
2


In [34]:
#пример 2.2.1
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


In [35]:
#пример 2.2.2
s1 = pd.Series([1,2,3,4,5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


In [36]:
#пример 2.2.3
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

In [37]:
#пример 2.2.4
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [38]:
#пример 2.2.5
dataframe.head(2) # взглянуть на первые несколько строк
dataframe.tail(3) # последние строки
dataframe.shape # кол-во строк и столбцов
dataframe.describe() # описательная статистика для любых числовых столбцов

Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [39]:
#пример 2.2.6
dataframe.iloc[1:4] # для выбора 1 или нескольких строк, либо значений (либо loc)

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [40]:
#пример 2.2.7
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [44]:
#задание 2.3.1
a = np.array((1, 2, 3))
b = np.array((4, 5, 6))

square = np.square(a - b) #почленно вычитаем и возводим в квадрат
sum_square = np.sum(square) #суммируем квадраты

distance = np.sqrt(sum_square) #берем корень из суммы
print(distance)

[9 9 9]


In [47]:
#задание 2.3.2
# Создать URL-адрес
url='https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv'
# Загрузить данные
dataframe=pd.read_csv(url)
# Показать семь строк
dataframe.head(10)

year       name gender  count
0  2000      Emily      F  25956
1  2000     Hannah      F  23082
2  2000    Madison      F  19968
3  2000     Ashley      F  17997
4  2000      Sarah      F  17702
5  2000     Alexis      F  17629
6  2000   Samantha      F  17265
7  2000    Jessica      F  15709
8  2000  Elizabeth      F  15099
9  2000     Taylor      F  15078

In [57]:
#задание 2.3.3.1
url='https://raw.githubusercontent.com/akmand/datasets/main/baby_names_2000.csv'
dataframe=pd.read_csv(url)
dataframe.head(10) # первые 10 строк
dataframe.tail(5) # последние 5 строк
dataframe.shape # кол-во строк и столбцов
dataframe.describe() # описательная статистика для любых числовых столбцов
dataframe.iloc[1:15] # для выбора 1 или нескольких строк, либо значений
dataframe[dataframe['gender'] == 'M'].head(5) # новый фрейм из условия

year         name gender  count
17655  2000        Jacob      M  34477
17656  2000      Michael      M  32037
17657  2000      Matthew      M  28573
17658  2000       Joshua      M  27537
17659  2000  Christopher      M  24932

In [68]:
#пример 3.2.1
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [69]:
#пример 3.2.2
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized

# Мы можем увидеть эффект стандартизации, обратившись к среднему значению и стандартному отклонению результата нашего решения
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


In [70]:
#пример 3.2.3
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [71]:
from sklearn.preprocessing import StandardScaler
dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')

# поменяли столбец sepal_length_cm
dataframe[['sepal_length_cm']] = MinMaxScaler().fit_transform(dataframe[['sepal_length_cm']])
# поменяли столбец sepal_width_cm
dataframe[['sepal_width_cm']] = StandardScaler().fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]